AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 lambda deployment bucket

Resources:
  MyLambdaDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mylambda-deployment


Outputs:
  MyLambdaBucketID:
    Value: !Ref MyLambdaDeploymentBucket
    Description: S3 bucket for lambda deployment